source "https://rubygems.org"

# gem "jekyll-remote-theme"
gem "github-pages", group: :jekyll_plugins
gem "jekyll"
# gem "minima"
#gem "just-the-docs", path: "/Users/kevinlin/projects/dendronv2/dendron-just-the-docs/"
